/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    SectionAbout: typeof import('./components/SectionAbout.vue')['default']
    SectionContacts: typeof import('./components/SectionContacts.vue')['default']
    SectionEducation: typeof import('./components/SectionEducation.vue')['default']
    SectionExperience: typeof import('./components/SectionExperience.vue')['default']
    SectionHero: typeof import('./components/SectionHero.vue')['default']
    SectionSkills: typeof import('./components/SectionSkills.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
